### ISSUE TITLE
Add ability to call exec commands on running containers within custom commands

### ISSUE THREAD

**Issue by thomas-anderson-bsl** [brightsparklabs/appcli#233]
We would like the ability to call 'docker exec' commands (or equivalent, based on orchestrator) on running containers in the appcli application from custom_commands.

This will allow us to write custom commands that can exec arbitrary commands on app containers, and give custom commands a much broader range of tasks it can do.

**Comment by thomas-anderson-bsl** [comment]
I think the approach would be adding functionality to the orchestrator to handle calling 'exec' on the given service name. For DockerComposeOrchestrator this should be pretty straightforward: https://docs.docker.com/compose/reference/exec/

**Comment by benjamin-wiffen** [comment]
@thomas-anderson-bsl Would it be acceptable to have exec run as a function of the service, ie:
`./appcli SERVICE execute "/bin/bash ls -al"`

**Comment by thomas-anderson-bsl** [comment]
Already discussed with Ben - this isn't the direction we are aiming to take this ticket. This also enables arbitrary code execution by anyone with privileges to run the application cli

What we really need is for the orchestrators to support running `exec`, and being able to call this internally from the main python entry script when creating custom commands

**Comment by thomas-anderson-bsl** [comment]
Completed as part of #234
