### ISSUE TITLE
Be more explicit when appcli instance fails to start.

### ISSUE THREAD

**Issue by benjamin-wiffen** [brightsparklabs/appcli#262]
When starting an `appcli` instance fails, this message gets shown:
```
2022-03-18T01:11:08+0000 INFO: START identity_stack ...
2022-03-18T01:11:09+0000 INFO: START command finished with code [1]
```
It would be better if we gave some indication of what went wrong:
```
2022-03-18T01:11:08+0000 INFO: START identity_stack ...
2022-03-18T01:11:09+0000 INFO: START command finished with code [1] "bash: /bin/bash: No such file or directory
"
```

**Comment by thomas-anderson-bsl** [comment]
Would these error messages come from the container logs?
Do you print all of the logs? If not, how do you know what port of the logs to print out?

What would you do if multiple containers failed to start?
How would you differentiate those logs?

**Comment by benjamin-wiffen** [comment]
I think as soon as one of the containers fails, then we cannot guarantee the integrity of the program, and we should abort the rest of the containers.
That means that we would only need to catch and display the error for the first container to fail.

**Comment by benjamin-wiffen** [comment]
Have discussed, and the program should alert the user which container(s) failed, along with giving them example commands to use to check the container error logs.

**Comment by al-jeyapal** [comment]
Resolved. Now prints command output for non-zero exit codes.
