### ISSUE TITLE
Cannot run launcher script via cron job

### ISSUE THREAD

**Issue by david-homley** [brightsparklabs/appcli#32]
The generated launcher script by default uses the argument `--tty` on the `docker run` command, which prevents the launcher script from being executed via cron jobs. In order to run the launcher via a cron job I have to manually delete this line from the launcher script.

For context:

I added a custom hook to an appcli-based project that would perform a backup of the host's conf and data directories, and as part of this piece I needed to setup a cron job to run this hook every night. 

However the job would always fail. Piping stdout/stderr to a file I could see the error message 'the input device is not a tty' once the cron job fired.

Deleting the `--tty` argument from the launcher script appears to fix this issue and allow the corn job to execute whilst not negatively impacting the regular operation of the launcher script.

**Comment by thomas-anderson-bsl** [comment]
I don't remember why we've left `--tty` and `--interactive` in there, or if there's a valid use case for it in the launcher.
I'm happy enough to remove these two options.
@al-jeyapal got any thoughts?

**Comment by al-jeyapal** [comment]
I'm not sure. Let's leave `--interactive` as this allows us to support prompting the user for input.
Drop the `--tty`.

**Comment by al-jeyapal** [comment]
Actually, I think we had to add `--tty` otherwise things like coloured output did not work.
E.g.
```
docker run --rm <appcli-container> --debug
# you see logging, but colours are ignored

docker run --rm --tty <appcli-container> --debug
# you see logging with colours
```

Perhaps it would be better if we can specify an option to the launcher script (or an env var?) to disable `--tty` if desired (e.g. in cron jobs / other non-tty cases):
```
<APP_NAME>_TTY=false /path/to/launcher
```

Check that would work in a cron job though
