### ISSUE TITLE
Allow execution of one off docker containers with dynamic arguments

### ISSUE THREAD

**Issue by david-homley** [brightsparklabs/appcli#33]
It would be nice to have some feature that allows the execution of 'one-off' docker containers that take in arguments that are dynamic e.g. they cannot be stored as settings as they change on each run.

For context: I want to setup an appcli-based project, where I run a CLI-based pipeline application wrapped in a docker container. This application take in a path to a folder of data to process, which will change each time I run the application. 

With the current version of applci, this is non-trivial to setup. e.g. I currently need to specify a `command` field in the `docker-compose` and pass in the path to the folder via environment variables.

**Comment by thomas-anderson-bsl** [comment]
Currently being implemented in feature/APPCLI-43-support-onceoff-runs
