### ISSUE TITLE
Enable modification of settings via EDITOR from a command

### ISSUE THREAD

**Issue by thomas-anderson-bsl** [brightsparklabs/appcli#37]
It would be useful to allow users to open the settings file with their $EDITOR directly from appcli commands.

This should look something like:
`<app> configure edit`

**Comment by glen-wiltshire-bsl** [comment]
After talking with @thomas-anderson-bsl it was decided that exposing the hosts $EDITOR to the appcli container should not be the approach here. While it is possible to do so it goes against the whole containerization idea, I've put one of these ways as the first commit to #54 as an example. 
The way we have decided to move forwards with this is to install a basic text editor (vim-tiny) into the appcli container and exposing it through the `<app> configure edit` command.
