### ISSUE TITLE
Change tag syntax to <VERSION>-baseline

### ISSUE THREAD

**Issue by glen-wiltshire-bsl** [brightsparklabs/appcli#42]
The tag for a clean baseline of a release that is added to the conf directory is named the same as a branch, this can be confusing.
The tag added to the conf directory should be changed to the format `<VERSION>-baseline`.

**Comment by thomas-anderson-bsl** [comment]
Hey @glen-wiltshire-bsl I'm going to request that we change the solution to this issue:
- rename the branches to `deployment/${VERSION}`,
- keep the tag as `${VERSION}`

Reasoning:
Tags should be named after the version they represent. As a 'base' tag, those are representing the clean installation of that specific version of an application. Therefore I'm happy to keep that as `${VERSION}`
The branch name isn't entirely clear and clashes with the tag name. By naming it `deployment/${VERSION}`, it makes it clear it's a branch (fits git flow and how we name git branches) and that it is a deployment of a specific version.
